package http

import (
	"encoding/json"
	"fmt"
	"net/http"
	"telegram-mini-app/internal/domain"
	"telegram-mini-app/internal/repository"
	"telegram-mini-app/pkg/telegram"
)

type TelegramAuthHandler struct {
	repo      *repository.Repository
	botToken  string
	jwtSecret []byte
}

func NewTelegramAuthHandler(repo *repository.Repository, botToken, jwtSecret string) *TelegramAuthHandler {
	return &TelegramAuthHandler{
		repo:      repo,
		botToken:  botToken,
		jwtSecret: []byte(jwtSecret),
	}
}

type TelegramAuthRequest struct {
	InitData string `json:"init_data"`
}

func (h *TelegramAuthHandler) LoginViaTelegram(w http.ResponseWriter, r *http.Request) {
	var req TelegramAuthRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil || req.InitData == "" {
		http.Error(w, "некорректное тело запроса", http.StatusBadRequest)
		return
	}

	tgUser, err := telegram.ValidateInitData(req.InitData, h.botToken)
	if err != nil {
		http.Error(w, "ошибка авторизации Telegram: "+err.Error(), http.StatusUnauthorized)
		return
	}

	// ИСПРАВЛЕНИЕ ЗДЕСЬ: Мы ВСЕГДА используем числовой ID телеграма как системный логин.
	// Это гарантирует, что мы всегда сможем отправить пуш-уведомление этому юзеру.
	username := fmt.Sprintf("tg_%d", tgUser.ID)

	user, err := h.repo.GetUserByUsername(r.Context(), username)
	if err != nil {
		// Если юзера с таким tg_ID еще нет, создаем его
		user, err = h.repo.CreateUser(r.Context(), username, "tg_autogenerated_hash", domain.RoleWorker)
		if err != nil {
			http.Error(w, "не удалось зарегистрировать пользователя Telegram", http.StatusInternalServerError)
			return
		}
	}

	claims := &Claims{
		UserID: user.ID,
		Role:   string(user.Role),
	}

	tokenString, err := generateToken(claims, h.jwtSecret)
	if err != nil {
		http.Error(w, "ошибка генерации токена", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{
		"token": tokenString,
	})
}
