package http

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"sort"
	"strings"
	"telegram-mini-app/internal/domain"
	"telegram-mini-app/internal/repository"
)

type TelegramAuthHandler struct {
	repo     *repository.Repository
	botToken string
}

func NewTelegramAuthHandler(repo *repository.Repository, botToken string) *TelegramAuthHandler {
	return &TelegramAuthHandler{
		repo:     repo,
		botToken: botToken,
	}
}

type TelegramAuthRequest struct {
	InitData string `json:"init_data"`
}

type TelegramUser struct {
	ID        int64  `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Username  string `json:"username"`
}

func ValidateInitData(initData, botToken string) (*TelegramUser, error) {
	values, err := url.ParseQuery(initData)
	if err != nil {
		return nil, fmt.Errorf("ошибка парсинга initData: %w", err)
	}

	hash := values.Get("hash")
	if hash == "" {
		return nil, fmt.Errorf("хэш отсутствует в initData")
	}

	values.Del("hash")

	var keys []string
	for k := range values {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var dataCheckArr []string
	for _, k := range keys {
		dataCheckArr = append(dataCheckArr, fmt.Sprintf("%s=%s", k, values.Get(k)))
	}
	dataCheckString := strings.Join(dataCheckArr, "\n")

	//Создаем секретный ключ HMAC-SHA256("WebAppData", botToken)
	secretKeyMac := hmac.New(sha256.New, []byte("WebAppData"))
	secretKeyMac.Write([]byte(botToken))
	secretKey := secretKeyMac.Sum(nil)

	//Считаем хэш от dataCheckString
	mac := hmac.New(sha256.New, secretKey)
	mac.Write([]byte(dataCheckString))
	calculatedHash := hex.EncodeToString(mac.Sum(nil))

	//Сравниваем подписи
	if !hmac.Equal([]byte(calculatedHash), []byte(hash)) {
		return nil, fmt.Errorf("недействительная подпись Telegram initData")
	}

	userStr := values.Get("user")
	if userStr == "" {
		return nil, fmt.Errorf("данные пользователя отсутствуют")
	}

	var tgUser TelegramUser
	if err := json.Unmarshal([]byte(userStr), &tgUser); err != nil {
		return nil, fmt.Errorf("ошибка парсинга данных пользователя: %w", err)
	}

	return &tgUser, nil
}

func (h *TelegramAuthHandler) LoginViaTelegram(w http.ResponseWriter, r *http.Request) {
	var req TelegramAuthRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil || req.InitData == "" {
		http.Error(w, "некорректное тело запроса", http.StatusBadRequest)
		return
	}

	tgUser, err := ValidateInitData(req.InitData, h.botToken)
	if err != nil {
		http.Error(w, "ошибка авторизации Telegram: "+err.Error(), http.StatusUnauthorized)
		return
	}

	username := tgUser.Username
	if username == "" {
		username = fmt.Sprintf("tg_%d", tgUser.ID)
	}

	user, err := h.repo.GetUserByUsername(r.Context(), username)
	if err != nil {
		user, err = h.repo.CreateUser(r.Context(), username, "tg_autogenerated_hash", domain.RoleWorker)
		if err != nil {
			http.Error(w, "не удалось зарегистрировать пользователя Telegram", http.StatusInternalServerError)
			return
		}
	}

	// Выдаем JWT токен
	claims := &Claims{
		UserID: user.ID,
		Role:   string(user.Role),
	}

	tokenString, err := generateToken(claims)
	if err != nil {
		http.Error(w, "ошибка генерации токена", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{
		"token": tokenString,
	})
}
